"""empty message

Revision ID: 57ad323eb01d
Revises: 
Create Date: 2020-11-29 23:02:23.223566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ad323eb01d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('userStatus', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_ID')
    )
    op.create_table('article',
    sa.Column('article_ID', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['user.user_ID'], ),
    sa.PrimaryKeyConstraint('article_ID')
    )
    op.create_table('users_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=True),
    sa.Column('article_ID', sa.Integer(), nullable=True),
    sa.Column('edited_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_ID'], ['article.article_ID'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['user.user_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_articles')
    op.drop_table('article')
    op.drop_table('user')
    # ### end Alembic commands ###
